export async function generateReportPDF(report: any) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(report.title || "Business Performance Report", 14, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated: ${report.generatedAt || new Date().toISOString().split("T")[0]}`, 14, y);
  y += 6;

  // Score badge
  if (report.overallScore) {
    const scoreColor: [number, number, number] = report.overallScore >= 75 ? [34, 197, 94] : report.overallScore >= 50 ? [245, 158, 11] : [239, 68, 68];
    doc.setFillColor(...scoreColor);
    doc.roundedRect(14, y, 60, 8, 2, 2, "F");
    doc.setTextColor(255);
    doc.setFontSize(9);
    doc.text(`Overall Score: ${report.overallScore}/100 — ${report.riskLevel?.toUpperCase() || "MEDIUM"} RISK`, 18, y + 5.5);
    doc.setTextColor(0);
    y += 14;
  }

  // Executive Summary
  doc.setDrawColor(200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary", 14, y);
  y += 6;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(report.executiveSummary || "", pageWidth - 28);
  doc.text(summaryLines, 14, y);
  y += summaryLines.length * 5 + 8;

  // Sections
  for (const section of report.sections || []) {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(section.heading, 14, y);
    y += 6;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const contentLines = doc.splitTextToSize(section.content || "", pageWidth - 28);
    doc.text(contentLines, 14, y);
    y += contentLines.length * 5 + 2;
    if (section.highlights?.length) {
      for (const h of section.highlights) {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFillColor(239, 246, 255);
        doc.roundedRect(14, y - 3, pageWidth - 28, 7, 1, 1, "F");
        doc.setFontSize(9);
        doc.text(`  •  ${h}`, 18, y + 1.5);
        y += 9;
      }
    }
    y += 6;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by BizAssist AI Hub — Powered by DeepSeek AI", pageWidth / 2, 285, { align: "center" });

  return doc;
}

export async function generateInvoicePDF(invoice: any) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Invoice header
  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 14, 22);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(invoice.invoiceNumber || `INV-${Date.now().toString().slice(-6)}`, 14, 32);
  doc.setFontSize(10);
  doc.text(`Date: ${invoice.date}`, pageWidth - 14, 22, { align: "right" });
  doc.text(`Due: ${invoice.dueDate}`, pageWidth - 14, 30, { align: "right" });
  doc.setTextColor(0);
  y = 50;

  // Seller & Buyer
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("FROM", 14, y);
  doc.text("BILL TO", pageWidth / 2 + 10, y);
  y += 5;
  doc.setTextColor(0);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(invoice.seller?.name || "BizAssist Business", 14, y);
  doc.text(invoice.buyer?.name || "Customer", pageWidth / 2 + 10, y);
  y += 5;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text(invoice.seller?.address || "Kuala Lumpur, Malaysia", 14, y);
  if (invoice.buyer?.phone) doc.text(`Phone: ${invoice.buyer.phone}`, pageWidth / 2 + 10, y);
  y += 12;

  // Line items table header
  doc.setFillColor(243, 244, 246);
  doc.rect(14, y - 4, pageWidth - 28, 9, "F");
  doc.setTextColor(100);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("DESCRIPTION", 18, y);
  doc.text("QTY", 120, y, { align: "center" });
  doc.text("UNIT PRICE", 145, y, { align: "right" });
  doc.text("AMOUNT", pageWidth - 18, y, { align: "right" });
  y += 10;

  // Line items
  doc.setTextColor(0);
  doc.setFont("helvetica", "normal");
  for (const item of invoice.lineItems || []) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(9);
    doc.text(item.description || "", 18, y);
    doc.text(String(item.quantity || 1), 120, y, { align: "center" });
    doc.text(`RM${(item.unitPrice || 0).toFixed(2)}`, 145, y, { align: "right" });
    doc.text(`RM${(item.subtotal || 0).toFixed(2)}`, pageWidth - 18, y, { align: "right" });
    y += 7;
  }

  // Divider
  y += 3;
  doc.setDrawColor(200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  // Totals
  const totalX = pageWidth - 14;
  doc.setFontSize(10);
  doc.text("Subtotal:", totalX - 50, y);
  doc.text(`RM${(invoice.subtotal || 0).toFixed(2)}`, totalX, y, { align: "right" });
  y += 6;
  doc.text(`Tax (${invoice.taxRate || "0%"}):`, totalX - 50, y);
  doc.text(`RM${(invoice.tax || 0).toFixed(2)}`, totalX, y, { align: "right" });
  y += 8;

  doc.setFillColor(30, 64, 175);
  doc.roundedRect(totalX - 60, y - 3, 60, 12, 2, 2, "F");
  doc.setTextColor(255);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL:", totalX - 55, y + 4);
  doc.text(`RM${(invoice.total || 0).toFixed(2)}`, totalX - 3, y + 4, { align: "right" });
  doc.setTextColor(0);
  y += 18;

  // Payment terms & notes
  if (y < 230) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`Payment Terms: ${invoice.paymentTerms || "Net 30 days"}`, 14, y);
    y += 6;
    if (invoice.notes) {
      doc.text(`Notes: ${invoice.notes}`, 14, y);
      y += 6;
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(invoice.footerMessage || "This is a computer-generated invoice.", pageWidth / 2, 282, { align: "center" });
  doc.text("Generated by BizAssist AI Hub", pageWidth / 2, 287, { align: "center" });

  return doc;
}
