/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/copilot': typeof CopilotRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/copilot': typeof CopilotRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/copilot': typeof CopilotRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/catalog'
    | '/copilot'
    | '/customers'
    | '/forecast'
    | '/import'
    | '/integrations'
    | '/intelligence'
    | '/meetings'
    | '/messages'
    | '/orders'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/catalog'
    | '/copilot'
    | '/customers'
    | '/forecast'
    | '/import'
    | '/integrations'
    | '/intelligence'
    | '/meetings'
    | '/messages'
    | '/orders'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/catalog'
    | '/copilot'
    | '/customers'
    | '/forecast'
    | '/import'
    | '/integrations'
    | '/intelligence'
    | '/meetings'
    | '/messages'
    | '/orders'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CatalogRoute: typeof CatalogRoute
  CopilotRoute: typeof CopilotRoute
  CustomersRoute: typeof CustomersRoute
  ForecastRoute: typeof ForecastRoute
  ImportRoute: typeof ImportRoute
  IntegrationsRoute: typeof IntegrationsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  MeetingsRoute: typeof MeetingsRoute
  MessagesRoute: typeof MessagesRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CatalogRoute: CatalogRoute,
  CopilotRoute: CopilotRoute,
  CustomersRoute: CustomersRoute,
  ForecastRoute: ForecastRoute,
  ImportRoute: ImportRoute,
  IntegrationsRoute: IntegrationsRoute,
  IntelligenceRoute: IntelligenceRoute,
  MeetingsRoute: MeetingsRoute,
  MessagesRoute: MessagesRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
